{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archon.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archon.labels" . | nindent 4 }}
type: Opaque
stringData:
  # These should be set via external secret management or values override
  SUPABASE_URL: {{ .Values.secrets.data.supabaseUrl | quote }}
  SUPABASE_SERVICE_KEY: {{ .Values.secrets.data.supabaseServiceKey | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.data.openaiApiKey | quote }}
  LOGFIRE_TOKEN: {{ .Values.secrets.data.logfireToken | quote }}
{{- end }}